apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 120340950114.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 120340950114.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 5de2928a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
